namespace: postgres-operator

commonLabels:
  app.kubernetes.io/name: pgo
  app.kubernetes.io/version: 5.0.4
  postgres-operator.crunchydata.com/control-plane: postgres-operator

bases:
- crd
- rbac/cluster
- manager

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.0.4-0

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: pgo
    path: ./patches/selectors.yaml
    # path is used for compatibility with version of kubectl prior to v1.21.0.
    # newer version of kubectl can use the inline patch below, which is the
    # preferred method going forward.
    # patch: |-
    #   - op: remove
    #     path: /spec/selector/matchLabels/app.kubernetes.io~1name
    #   - op: remove
    #     path: /spec/selector/matchLabels/app.kubernetes.io~1version
