---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-upgrade
  labels:
    {{- include "install.labels" . | nindent 4 }}
    {{- include "install.upgradeLabels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels:
      {{- include "install.upgradeLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "install.upgradeLabels" . | nindent 8 }}
    spec:
      {{- include "install.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ include "install.serviceAccountName" . }}-upgrade
      containers:
      - name: operator
        image: {{ required ".Values.controllerImages.upgrade is required" .Values.controllerImages.upgrade | quote }}
        env:
        - name: CRUNCHY_DEBUG
          value: {{ .Values.debug | ne false | quote }}
        {{- if .Values.singleNamespace }}
        - name: PGO_TARGET_NAMESPACE
          valueFrom: { fieldRef: { apiVersion: v1, fieldPath: metadata.namespace } }
        {{- end }}
        {{- if .Values.workers }}
        - name: PGO_WORKERS
          value: {{ .Values.workers | quote }}
        {{- end }}
        {{- include "install.relatedImages" . | indent 8 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: [ALL] }
          readOnlyRootFilesystem: true
          runAsNonRoot: true
