kind: Component
images:
- name: image-pgadmin
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4
  newTag: ubi9-9.8-2542
- name: image-pgbackrest
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest
  newTag: ubi9-2.56.0-2542
- name: image-pgbouncer
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer
  newTag: ubi9-1.24-2542
- name: image-postgres-exporter
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter
  newTag: ubi9-0.17.1-2542
- name: image-postgres-operator-5.8
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi9-5.8.4-0
- name: image-crunchy-postgres-15
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-15.14-2542
- name: image-crunchy-postgres-16
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-16.10-2542
- name: image-crunchy-postgres-17
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-17.6-2542
- name: image-crunchy-postgres-18
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-18.0-2542
- name: image-crunchy-upgrade
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade
  newTag: ubi9-18.0-2542
- name: image-crunchy-postgres-15-gis-3.3
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-15.14-3.3-2542
- name: image-crunchy-postgres-16-gis-3.3
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-16.10-3.3-2542
- name: image-crunchy-postgres-16-gis-3.4
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-16.10-3.4-2542
- name: image-crunchy-postgres-17-gis-3.4
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.6-3.4-2542
- name: image-crunchy-postgres-17-gis-3.5
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.6-3.5-2542
- name: image-crunchy-postgres-17-gis-3.6
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.6-3.6-2542
- name: image-crunchy-postgres-18-gis-3.6
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-18.0-3.6-2542
