apiVersion: v2
name: pgo
description: Installer for PGO, the open source Postgres Operator from Crunchy Data

type: application
# The version below should match the version on the PostgresCluster CRD
version: 5.3.1
appVersion: 5.3.1
