---
# controllerImages are used to run the operator's controllers.
# The cluster image defined below runs the PostgresCluster and PGUpgrade controllers.
controllerImages:
  cluster: registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.6.1-0

# relatedImages are used when an image is omitted from PostgresCluster, PGAdmin or PGUpgrade specs.
relatedImages:
  postgres_16:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.4-0
  postgres_16_gis_3.4:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-16.4-3.4-0
  postgres_16_gis_3.3:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-16.4-3.3-0
  postgres_15:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.8-0
  postgres_15_gis_3.3:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.8-3.3-0
  pgadmin:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-29
  pgbackrest:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.52.1-1
  pgbouncer:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.22-4
  pgexporter:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-0.15.0-10
  pgupgrade:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.6.1-0
  standalone_pgadmin:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-8.10-0

# singleNamespace controls where PGO watches for PostgresClusters. When false,
# PGO watches for and responds to PostgresClusters in all namespaces. When true,
# PGO watches only the namespace in which it is installed.
singleNamespace: false

# debug allows you to enable or disable the "debug" level of logging.
debug: true

# imagePullSecretNames is a list of secret names to use for pulling controller images.
# More info: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecretNames: []

# Resource configuration of the PostgresCluster and PGUpgrade controllers.
resources:
  controller: {}
# Define custom labels for PGO pods
# Note: Defining labels that overlap with any Crunchy Data label, for example,
# postgres-operator.crunchydata.com, will cause an error
# customPodLabels:
#  example.com: custom-label

# Enable feature gates for PGO, by explicitly seting the value for the flags
# features:
#   AutoGrowVolumes: true
#   Feature2: false
#   Feature3: somevalue

# Define extra environment variables for the chart, which will get added to the container's env
# extraEnv:
#   - name: MY_VAR
#     value: "myvalue"
#   - name: MY_CONFIGMAP_VAR
#     valueFrom:
#       configMapKeyRef:
#         name: s3-settings
#         key: bucket
#   - name: MY_SECRET_VAR
#     valueFrom:
#       secretKeyRef:
#         name: s3-secret
#         key: key

# Override environment variables entirely !!DANGEROUS!!
# envOverride:
#   - name: PG_DEBUG
#     value: "true"