---
## Provide image repository and tag
image:
  image: registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.1.0-0

relatedImages:
  postgres_14:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.2-1
  postgres_14_gis_3.1:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-14.2-3.1-1
  postgres_13:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.6-1
  postgres_13_gis_3.1:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-13.6-3.1-1
  pgadmin:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-0
  pgbackrest:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
  pgbouncer:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
  pgexporter:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.0-0
    

# singleNamespace determines how to install PGO to watch namesapces. If set to
# false, PGO will watch for Postgres clusters in all namesapces Setting to
# "true" will instruct PGO to only watch for Postgres clusters in the namespace
# that it is installed in. Defaults to the value below.
singleNamespace: false

# debug allows you to enable or disable the "debug" level of logging.
# Defaults to the value below.
debug: true
