---
## Provide image repository and tag
image:
  image: registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.0.4-0

relatedImages:
  postgres_14:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.1-0
  postgres_14_gis_3.1:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos8-14.1-3.1-0
  postgres_13:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
  postgres_13_gis_3.1:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos8-13.5-3.1-0
  pgbackrest:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
  pgbouncer:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.16-0
  pgexporter:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0

# singleNamespace determines how to install PGO to watch namesapces. If set to
# false, PGO will watch for Postgres clusters in all namesapces Setting to
# "true" will instruct PGO to only watch for Postgres clusters in the namespace
# that it is installed in. Defaults to the value below.
singleNamespace: false

# debug allows you to enable or disable the "debug" level of logging.
# Defaults to the value below.
debug: true
